// GENERATED by diff_harness/extract_corpus.py -- do not edit by hand.
// Upstream corpus for the maintainer-only differential harness, derived
// from the pinned upstream test sources in .upstream-pinned/. See
// extract_corpus.py for the derivation method.
#ifndef ROBOTSTXT_DIFF_HARNESS_CORPUS_DATA_H_
#define ROBOTSTXT_DIFF_HARNESS_CORPUS_DATA_H_

#include <string>
#include <vector>

#include "case_generator.h"

namespace robotstxt_diff {

// Returns the upstream-derived corpus of differential cases.
inline std::vector<DiffCase> UpstreamCorpus() {
  std::vector<DiffCase> c;
  c.push_back(DiffCase{"", "FooBot", ""});
  c.push_back(DiffCase{"user-agent: FooBot\\ndisallow: /\\n", "", ""});
  c.push_back(DiffCase{"user-agent: FooBot\\ndisallow: /\\n", "FooBot", ""});
  c.push_back(DiffCase{"", "", ""});
  c.push_back(DiffCase{"user-agent: FooBot\\ndisallow: /\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"foo: FooBot\\nbar: /\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"user-agent FooBot\\ndisallow /\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"allow: /foo/bar/\\n\\nuser-agent: FooBot\\ndisallow: /\\nallow: /x/\\nuser-agent: BarBot\\ndisallow: /\\nallow: /y/\\n\\n\\nallow: /w/\\nuser-agent: BazBot\\n\\nuser-agent: FooBot\\nallow: /z/\\ndisallow: /\\n", "FooBot", "http://foo.bar/x/b"});
  c.push_back(DiffCase{"allow: /foo/bar/\\n\\nuser-agent: FooBot\\ndisallow: /\\nallow: /x/\\nuser-agent: BarBot\\ndisallow: /\\nallow: /y/\\n\\n\\nallow: /w/\\nuser-agent: BazBot\\n\\nuser-agent: FooBot\\nallow: /z/\\ndisallow: /\\n", "FooBot", "http://foo.bar/z/d"});
  c.push_back(DiffCase{"allow: /foo/bar/\\n\\nuser-agent: FooBot\\ndisallow: /\\nallow: /x/\\nuser-agent: BarBot\\ndisallow: /\\nallow: /y/\\n\\n\\nallow: /w/\\nuser-agent: BazBot\\n\\nuser-agent: FooBot\\nallow: /z/\\ndisallow: /\\n", "FooBot", "http://foo.bar/y/c"});
  c.push_back(DiffCase{"allow: /foo/bar/\\n\\nuser-agent: FooBot\\ndisallow: /\\nallow: /x/\\nuser-agent: BarBot\\ndisallow: /\\nallow: /y/\\n\\n\\nallow: /w/\\nuser-agent: BazBot\\n\\nuser-agent: FooBot\\nallow: /z/\\ndisallow: /\\n", "BarBot", "http://foo.bar/y/c"});
  c.push_back(DiffCase{"allow: /foo/bar/\\n\\nuser-agent: FooBot\\ndisallow: /\\nallow: /x/\\nuser-agent: BarBot\\ndisallow: /\\nallow: /y/\\n\\n\\nallow: /w/\\nuser-agent: BazBot\\n\\nuser-agent: FooBot\\nallow: /z/\\ndisallow: /\\n", "BarBot", "http://foo.bar/w/a"});
  c.push_back(DiffCase{"allow: /foo/bar/\\n\\nuser-agent: FooBot\\ndisallow: /\\nallow: /x/\\nuser-agent: BarBot\\ndisallow: /\\nallow: /y/\\n\\n\\nallow: /w/\\nuser-agent: BazBot\\n\\nuser-agent: FooBot\\nallow: /z/\\ndisallow: /\\n", "BarBot", "http://foo.bar/z/d"});
  c.push_back(DiffCase{"allow: /foo/bar/\\n\\nuser-agent: FooBot\\ndisallow: /\\nallow: /x/\\nuser-agent: BarBot\\ndisallow: /\\nallow: /y/\\n\\n\\nallow: /w/\\nuser-agent: BazBot\\n\\nuser-agent: FooBot\\nallow: /z/\\ndisallow: /\\n", "BazBot", "http://foo.bar/z/d"});
  c.push_back(DiffCase{"allow: /foo/bar/\\n\\nuser-agent: FooBot\\ndisallow: /\\nallow: /x/\\nuser-agent: BarBot\\ndisallow: /\\nallow: /y/\\n\\n\\nallow: /w/\\nuser-agent: BazBot\\n\\nuser-agent: FooBot\\nallow: /z/\\ndisallow: /\\n", "FooBot", "http://foo.bar/foo/bar/"});
  c.push_back(DiffCase{"allow: /foo/bar/\\n\\nuser-agent: FooBot\\ndisallow: /\\nallow: /x/\\nuser-agent: BarBot\\ndisallow: /\\nallow: /y/\\n\\n\\nallow: /w/\\nuser-agent: BazBot\\n\\nuser-agent: FooBot\\nallow: /z/\\ndisallow: /\\n", "BarBot", "http://foo.bar/foo/bar/"});
  c.push_back(DiffCase{"allow: /foo/bar/\\n\\nuser-agent: FooBot\\ndisallow: /\\nallow: /x/\\nuser-agent: BarBot\\ndisallow: /\\nallow: /y/\\n\\n\\nallow: /w/\\nuser-agent: BazBot\\n\\nuser-agent: FooBot\\nallow: /z/\\ndisallow: /\\n", "BazBot", "http://foo.bar/foo/bar/"});
  c.push_back(DiffCase{"User-agent: BarBot\\nSitemap: https://foo.bar/sitemap\\nUser-agent: *\\nDisallow: /\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-agent: BarBot\\nSitemap: https://foo.bar/sitemap\\nUser-agent: *\\nDisallow: /\\n", "BarBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-agent: FooBot\\nInvalid-Unknown-Line: unknown\\nUser-agent: *\\nDisallow: /\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-agent: FooBot\\nInvalid-Unknown-Line: unknown\\nUser-agent: *\\nDisallow: /\\n", "BarBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"USER-AGENT: FooBot\\nALLOW: /x/\\nDISALLOW: /\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"user-agent: FooBot\\nallow: /x/\\ndisallow: /\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"uSeR-aGeNt: FooBot\\nAlLoW: /x/\\ndIsAlLoW: /\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"USER-AGENT: FooBot\\nALLOW: /x/\\nDISALLOW: /\\n", "FooBot", "http://foo.bar/a/b"});
  c.push_back(DiffCase{"user-agent: FooBot\\nallow: /x/\\ndisallow: /\\n", "FooBot", "http://foo.bar/a/b"});
  c.push_back(DiffCase{"uSeR-aGeNt: FooBot\\nAlLoW: /x/\\ndIsAlLoW: /\\n", "FooBot", "http://foo.bar/a/b"});
  c.push_back(DiffCase{"User-Agent: FOO BAR\\nAllow: /x/\\nDisallow: /\\n", "Foo", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-Agent: foo bar\\nAllow: /x/\\nDisallow: /\\n", "Foo", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-Agent: FoO bAr\\nAllow: /x/\\nDisallow: /\\n", "Foo", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-Agent: FOO BAR\\nAllow: /x/\\nDisallow: /\\n", "Foo", "http://foo.bar/a/b"});
  c.push_back(DiffCase{"User-Agent: foo bar\\nAllow: /x/\\nDisallow: /\\n", "Foo", "http://foo.bar/a/b"});
  c.push_back(DiffCase{"User-Agent: FoO bAr\\nAllow: /x/\\nDisallow: /\\n", "Foo", "http://foo.bar/a/b"});
  c.push_back(DiffCase{"User-Agent: FOO BAR\\nAllow: /x/\\nDisallow: /\\n", "foo", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-Agent: foo bar\\nAllow: /x/\\nDisallow: /\\n", "foo", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-Agent: FoO bAr\\nAllow: /x/\\nDisallow: /\\n", "foo", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-Agent: FOO BAR\\nAllow: /x/\\nDisallow: /\\n", "foo", "http://foo.bar/a/b"});
  c.push_back(DiffCase{"User-Agent: foo bar\\nAllow: /x/\\nDisallow: /\\n", "foo", "http://foo.bar/a/b"});
  c.push_back(DiffCase{"User-Agent: FoO bAr\\nAllow: /x/\\nDisallow: /\\n", "foo", "http://foo.bar/a/b"});
  c.push_back(DiffCase{"User-Agent: *\\nDisallow: /\\nUser-Agent: Foo Bar\\nAllow: /x/\\nDisallow: /\\n", "Foo", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-Agent: *\\nDisallow: /\\nUser-Agent: Foo Bar\\nAllow: /x/\\nDisallow: /\\n", "Foo Bar", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"user-agent: *\\nallow: /\\nuser-agent: FooBot\\ndisallow: /\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"user-agent: *\\nallow: /\\nuser-agent: FooBot\\ndisallow: /\\n", "BarBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"user-agent: FooBot\\nallow: /\\nuser-agent: BarBot\\ndisallow: /\\nuser-agent: BazBot\\ndisallow: /\\n", "QuxBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"user-agent: FooBot\\ndisallow: /x/\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"user-agent: FooBot\\ndisallow: /X/\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"user-agent: FooBot\\ndisallow: /x/page.html\\nallow: /x/\\n", "FooBot", "http://foo.bar/x/page.html"});
  c.push_back(DiffCase{"user-agent: FooBot\\nallow: /x/page.html\\ndisallow: /x/\\n", "FooBot", "http://foo.bar/x/page.html"});
  c.push_back(DiffCase{"user-agent: FooBot\\nallow: /x/page.html\\ndisallow: /x/\\n", "FooBot", "http://foo.bar/x/"});
  c.push_back(DiffCase{"user-agent: FooBot\\ndisallow: \\nallow: \\n", "FooBot", "http://foo.bar/x/page.html"});
  c.push_back(DiffCase{"user-agent: FooBot\\ndisallow: /\\nallow: /\\n", "FooBot", "http://foo.bar/x/page.html"});
  c.push_back(DiffCase{"user-agent: FooBot\\ndisallow: /x/page.html\\nallow: /x/page.html\\n", "FooBot", "http://foo.bar/x/page.html"});
  c.push_back(DiffCase{"user-agent: FooBot\\nallow: /page\\ndisallow: /*.html\\n", "FooBot", "http://foo.bar/page.html"});
  c.push_back(DiffCase{"user-agent: FooBot\\nallow: /page\\ndisallow: /*.html\\n", "FooBot", "http://foo.bar/page"});
  c.push_back(DiffCase{"user-agent: FooBot\\nallow: /x/page.\\ndisallow: /*.html\\n", "FooBot", "http://foo.bar/x/page.html"});
  c.push_back(DiffCase{"user-agent: FooBot\\nallow: /x/page.\\ndisallow: /*.html\\n", "FooBot", "http://foo.bar/x/y.html"});
  c.push_back(DiffCase{"User-agent: *\\nDisallow: /x/\\nUser-agent: FooBot\\nDisallow: /y/\\n", "FooBot", "http://foo.bar/x/page"});
  c.push_back(DiffCase{"User-agent: *\\nDisallow: /x/\\nUser-agent: FooBot\\nDisallow: /y/\\n", "FooBot", "http://foo.bar/y/page"});
  c.push_back(DiffCase{"User-agent: FooBot\\nDisallow: /\\nAllow: /foo/bar?qux=taz&baz=http://foo.bar?tar&par\\n", "FooBot", "http://foo.bar/foo/bar?qux=taz&baz=http://foo.bar?tar&par"});
  c.push_back(DiffCase{"User-agent: FooBot\\nDisallow: /\\nAllow: /foo/bar/\xe3""\x83""\x84""\\n", "FooBot", "http://foo.bar/foo/bar/%E3%83%84"});
  c.push_back(DiffCase{"User-agent: FooBot\\nDisallow: /\\nAllow: /foo/bar/\xe3""\x83""\x84""\\n", "FooBot", "http://foo.bar/foo/bar/\xe3""\x83""\x84"""});
  c.push_back(DiffCase{"User-agent: FooBot\\nDisallow: /\\nAllow: /foo/bar/%E3%83%84\\n", "FooBot", "http://foo.bar/foo/bar/%E3%83%84"});
  c.push_back(DiffCase{"User-agent: FooBot\\nDisallow: /\\nAllow: /foo/bar/%E3%83%84\\n", "FooBot", "http://foo.bar/foo/bar/\xe3""\x83""\x84"""});
  c.push_back(DiffCase{"User-agent: FooBot\\nDisallow: /\\nAllow: /foo/bar/%62%61%7A\\n", "FooBot", "http://foo.bar/foo/bar/baz"});
  c.push_back(DiffCase{"User-agent: FooBot\\nDisallow: /\\nAllow: /foo/bar/%62%61%7A\\n", "FooBot", "http://foo.bar/foo/bar/%62%61%7A"});
  c.push_back(DiffCase{"User-agent: FooBot\\nDisallow: /foo/bar/quz\\nAllow: /foo/*/qux\\n", "FooBot", "http://foo.bar/foo/bar/quz"});
  c.push_back(DiffCase{"User-agent: FooBot\\nDisallow: /foo/bar/quz\\nAllow: /foo/*/qux\\n", "FooBot", "http://foo.bar/foo/quz"});
  c.push_back(DiffCase{"User-agent: FooBot\\nDisallow: /foo/bar/quz\\nAllow: /foo/*/qux\\n", "FooBot", "http://foo.bar/foo//quz"});
  c.push_back(DiffCase{"User-agent: FooBot\\nDisallow: /foo/bar/quz\\nAllow: /foo/*/qux\\n", "FooBot", "http://foo.bar/foo/bax/quz"});
  c.push_back(DiffCase{"User-agent: FooBot\\nDisallow: /foo/bar$\\nAllow: /foo/bar/qux\\n", "FooBot", "http://foo.bar/foo/bar"});
  c.push_back(DiffCase{"User-agent: FooBot\\nDisallow: /foo/bar$\\nAllow: /foo/bar/qux\\n", "FooBot", "http://foo.bar/foo/bar/qux"});
  c.push_back(DiffCase{"User-agent: FooBot\\nDisallow: /foo/bar$\\nAllow: /foo/bar/qux\\n", "FooBot", "http://foo.bar/foo/bar/"});
  c.push_back(DiffCase{"User-agent: FooBot\\nDisallow: /foo/bar$\\nAllow: /foo/bar/qux\\n", "FooBot", "http://foo.bar/foo/bar/baz"});
  c.push_back(DiffCase{"User-agent: FooBot\\n# Disallow: /\\nDisallow: /foo/quz#qux\\nAllow: /\\n", "FooBot", "http://foo.bar/foo/bar"});
  c.push_back(DiffCase{"User-agent: FooBot\\n# Disallow: /\\nDisallow: /foo/quz#qux\\nAllow: /\\n", "FooBot", "http://foo.bar/foo/quz"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "foobot", "http://foo.com/allowed-slash/"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "foobot", "http://foo.com/allowed-slash/index.htm"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "foobot", "http://foo.com/allowed-slash/index.html"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "foobot", "http://foo.com/anyother-url"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/fux"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/bar"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/fish"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/fish.html"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/fish/salmon.html"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/fishheads"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/fishheads/yummy.html"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/fish.html?id=anything"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/Fish.asp"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/catfish"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/?id=fish"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/Fish.bar"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/fish/"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/fish/salmon"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/fish/?salmon"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/fish/?id=anything"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/Fish/Salmon.html"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/filename.php"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/folder/filename.php"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/folder/filename.php?parameters"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar//folder/any.php.file.html"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/filename.php/"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/index?f=filename.php/"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/php/"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/index?php"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/windows.PHP"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/filename.php?parameters"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/filename.php5"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/filename?php"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/aaaphpaaa"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar//windows.PHP"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/fish.php"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/fishheads/catfish.php?parameters"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/Fish.PHP"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/x/page.html"});
  c.push_back(DiffCase{"User-Agent: foo\\nAllow: /some/path\\nUser-Agent: bar\\n\\n\\nDisallow: /\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-Agent: foo\\nAllow: /some/path\\nUser-Agent: bar\\n\\n\\nDisallow: /\\n", "*", "http://foo.bar/"});
  c.push_back(DiffCase{"User-Agent: foo\\r\\nAllow: /some/path\\r\\nUser-Agent: bar\\r\\n\\r\\n\\r\\nDisallow: /\\r\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-Agent: foo\\r\\nAllow: /some/path\\r\\nUser-Agent: bar\\r\\n\\r\\n\\r\\nDisallow: /\\r\\n", "*", "http://foo.bar/"});
  c.push_back(DiffCase{"User-Agent: foo\\rAllow: /some/path\\rUser-Agent: bar\\r\\r\\rDisallow: /\\r", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-Agent: foo\\rAllow: /some/path\\rUser-Agent: bar\\r\\r\\rDisallow: /\\r", "*", "http://foo.bar/"});
  c.push_back(DiffCase{"User-Agent: foo\\nAllow: /some/path\\nUser-Agent: bar\\n\\n\\nDisallow: /", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-Agent: foo\\nAllow: /some/path\\nUser-Agent: bar\\n\\n\\nDisallow: /", "*", "http://foo.bar/"});
  c.push_back(DiffCase{"User-Agent: foo\\nAllow: /some/path\\r\\nUser-Agent: bar\\n\\r\\n\\nDisallow: /", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-Agent: foo\\nAllow: /some/path\\r\\nUser-Agent: bar\\n\\r\\n\\nDisallow: /", "*", "http://foo.bar/"});
  c.push_back(DiffCase{"\\xEF\\xBB\\xBFUser-Agent: foo\\nAllow: /AnyValue\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"\\xEF\\xBB\\xBFUser-Agent: foo\\nAllow: /AnyValue\\n", "*", "http://foo.bar/"});
  c.push_back(DiffCase{"\\xEF\\xBBUser-Agent: foo\\nAllow: /AnyValue\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"\\xEF\\xBBUser-Agent: foo\\nAllow: /AnyValue\\n", "*", "http://foo.bar/"});
  c.push_back(DiffCase{"\\xEFUser-Agent: foo\\nAllow: /AnyValue\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"\\xEFUser-Agent: foo\\nAllow: /AnyValue\\n", "*", "http://foo.bar/"});
  c.push_back(DiffCase{"\\xEF\\x11\\xBFUser-Agent: foo\\nAllow: /AnyValue\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"\\xEF\\x11\\xBFUser-Agent: foo\\nAllow: /AnyValue\\n", "*", "http://foo.bar/"});
  c.push_back(DiffCase{"User-Agent: foo\\n\\xEF\\xBB\\xBFAllow: /AnyValue\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-Agent: foo\\n\\xEF\\xBB\\xBFAllow: /AnyValue\\n", "*", "http://foo.bar/"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "FooBot", "http://foo.bar/x/y"});
  c.push_back(DiffCase{"User-Agent: *\\nAllow: /allowed-slash/index.html\\nDisallow: /\\n", "*", "http://foo.bar/"});
  return c;
}

}  // namespace robotstxt_diff
#endif  // ROBOTSTXT_DIFF_HARNESS_CORPUS_DATA_H_
